import { Router } from 'express';
import { getMe, updateMe, updatePreferences } from '../controllers/userController.js';
import { requireAuth } from '../middleware/auth.js';
import { validate } from '../middleware/validate.js';
import { preferenceSchema, profileSchema } from '../validators/userValidators.js';
const router = Router();
router.use(requireAuth);
router.get('/me', getMe);
router.patch('/me', validate(profileSchema), updateMe);
router.patch('/me/preferences', validate(preferenceSchema), updatePreferences);
export default router;
